# Generated by Django 5.1.3 on 2024-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_rename_product_orderitem_product_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
